<style type="text/css">
    label{width:5%;float:left;}
</style>

<?php
    $title = 'File Upload Form';
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
//echo "<pre>";
//print_r($form);die;

$form->setAttribute('action', $this->basepath('users/fupload/faction'));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get("id"));echo "<br>";
echo $this->formRow($form->get("fupload"));echo "<br>";

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
//echo $this->formCollection($form);
?>


